name: Build Application image

on:
  push:
    branches:
      - dev

jobs:
  tests: 
    runs-on: ubuntu-latest
    steps:
      - name: Chekout git files
        uses: actions/checkout@v3
        
      - name: Start docker to run tests
        run: docker compose -f ./docker/docker-compose-test.yml up -d

      - name: Use Node.js Version 20.X
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:ci
        env:
          WEBHOOK_SECRET: "U0dWc2JHOGdWl5YkdRaElRPT0: "
          CLERK_JWT_SECRET_KEY: "kfvbnkfnsdmfnmfpdnmdpfmnmn"
          SECRET_KEY_SESSION: "jnobuidgbnofdiojnarejnmapbnsvmw459obkphonvMVOPGIANBNHORV"
          MONGO_URI: "mongodb://127.0.0.1:27017/rpg-log"
          DATABASE_URL: "postgres://test:test@localhost:5432/test"
          DATABASE_TEST_URL: "postgres://test:test@localhost:5432/test"
          PORT: 3000

      - name: Stop Containers
        run: docker compose -f ./docker/docker-compose-test.yml down

  build:
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
    - name: Chekout git files
      uses: actions/checkout@v3
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKE }}

    - name: Build and push 
      uses: docker/build-push-action@v6  
      with:
          context: .
          platforms: linux/amd64,linux/arm64  
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/temvagamestreapi:${{github.sha}},${{secrets.DOCKERHUB_USERNAME}}/temvagamestreapi:latest
