name: Test in pull requests

on:
  pull_request:
    branches:
      - dev

jobs:
  tests: 
    runs-on: ubuntu-latest
    steps:
      - name: Chekout git files
        uses: actions/checkout@v3
        
      - name: Start docker to run tests
        run: docker compose -f ./docker/docker-compose-test.yml up -d

      - name: Use Node.js Version 20.X
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:ci

      - name: Stop Containers
        run: docker compose -f ./docker/docker-compose-test.yml down
