name: Test in pull requests

on:
  pull_request:
    branches:
      - dev

jobs:
  tests: 
    runs-on: ubuntu-latest
    steps:
      - name: Chekout git files
        uses: actions/checkout@v3

      - uses: benjlevesque/short-sha@v3.0
        id: short-sha
        with:
          length: 7

      - run: echo $SHA
        env:
          SHA: ${{ steps.short-sha.outputs.sha }}

      - run: echo $SHA
        env:
          SHA: ${{ env.SHA }}

      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          up-flags: "-d"
          compose-file: "./docker/docker-compose-test.yml"

      - name: Use Node.js Version 20.X
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:ci
        env:
          WEBHOOK_SECRET: "U0dWc2JHOGdWl5YkdRaElRPT0="
          CLERK_JWT_SECRET_KEY: "kfvbnkfnsdmfnmfpdnmdpfmnmn"
          SECRET_KEY_SESSION: "jnobuidgbnofdiojnarejnmapbnsvmw459obkphonvMVOPGIANBNHORV"
          MONGO_URI: "mongodb://127.0.0.1:27017/rpg-log"
          DATABASE_URL: "postgres://test:test@localhost:5432/test"
          DATABASE_TEST_URL: "postgres://test:test@localhost:5432/test"
          PORT: 3000
